[env:esp32dev]
platform = espressif32@6.4.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D USER_SETUP_LOADED
    -D ST7735_DRIVER
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=16
    -D TFT_RST=17
    -D TFT_MISO=-1
    -D SPI_FREQUENCY=27000000
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
    -D SMOOTH_FONT
    -D BOARD_ESP32_WROOM

lib_deps =
    bodmer/TFT_eSPI
    bblanchon/ArduinoJson
    h2zero/NimBLE-Arduino
    crankyoldgit/IRremoteESP8266
    adafruit/Adafruit PN532
    nrf24/RF24
    sui77/rc-switch
    kosme/arduinoFFT
    xreef/PCF8574_library

lib_ldf_mode = deep+

board_build.partitions = default.csv
