; PlatformIO – ESP32-WROOM TYPHON (Bluedroid BLE + Wi-Fi)
; Partition: huge_app for Bluedroid binary size

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bodmer/TFT_eSPI@^2.5.43

build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D ST7735_BLACKTAB=1
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=16
    -D TFT_RST=17
    -D TFT_BL=-1
    -D TOUCH_CS=-1
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=0
    -D SPI_FREQUENCY=27000000
    -D SPI_READ_FREQUENCY=20000000
    -D CORE_DEBUG_LEVEL=1
    -D ARDUINO_USB_MODE=0
    -Wl,--wrap=ieee80211_raw_frame_sanity_check

board_build.partitions = huge_app.csv
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
